image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle config disable_checksum_validation true
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/w1HchFc6M8H99QFSCUA3JTVNhovbWHsigfMcn4A5boc.html ./public/.well-known/acme-challenge/w1HchFc6M8H99QFSCUA3JTVNhovbWHsigfMcn4A5boc
  - cp ./public/.well-known/acme-challenge/hR0BUwHfrmGOmhDAWEshmJohCZ6jckRqfcjD4lUmdfI.html ./public/.well-known/acme-challenge/hR0BUwHfrmGOmhDAWEshmJohCZ6jckRqfcjD4lUmdfI
  - cp ./public/.well-known/acme-challenge/DB3MmQErAsp2IwHl1XO1S8CesFwh-816vO37fQiftLQ.html ./public/.well-known/acme-challenge/DB3MmQErAsp2IwHl1XO1S8CesFwh-816vO37fQiftLQ
  artifacts:
    paths:
    - public
  only:
  - master
